### ISSUE TITLE
File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by nquevedo-jcdecaux** [codyhouse/style-guide-template#1]
Hello, I downloaded the .zip file and tried integrating it with Laravel. However, it keeps showing this error:

`@import 'partials/basic-style';
^
      File to import not found or unreadable: bourbon.`

I have searched in Google and none of the solutions presented seem to work. Do you have any insights on how to solve this?

Thanks

**Comment by sebastiano-guerriero** [comment]
Hi there 👋 It looks like the SASS partials have not been included. They are inside the "partials" folder. Besides, this resource relies on the old version of Bourbon https://www.bourbon.io/. I suggest you remove the dependency (and replace the mixins with your own). We're removing Bourbon from all our resources, but it'll take time for us to update them all.
